<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::truncate();
        $sql = "INSERT INTO `countries` (`id`, `phone`, `code`, `name`) VALUES
                    (1, 93, 'AF', 'Afganistán'),
                    (2, 358, 'AX', 'Islas Aland'),
                    (3, 355, 'AL', 'Albania'),
                    (4, 213, 'DZ', 'Argelia'),
                    (5, 1684, 'AS', 'Samoa Americana'),
                    (6, 376, 'AD', 'Andorra'),
                    (7, 244, 'AO', 'Angola'),
                    (8, 1264, 'AI', 'Anguila'),
                    (9, 672, 'AQ', 'Antártida'),
                    (10, 1268, 'AG', 'Antigua y Barbuda'),
                    (11, 54, 'AR', 'Argentina'),
                    (12, 374, 'AM', 'Armenia'),
                    (13, 297, 'AW', 'Aruba'),
                    (14, 61, 'AU', 'Australia'),
                    (15, 43, 'AT', 'Austria'),
                    (16, 994, 'AZ', 'Azerbaiyán'),
                    (17, 1242, 'BS', 'Bahamas'),
                    (18, 973, 'BH', 'Bahréin'),
                    (19, 880, 'BD', 'Bangladesh'),
                    (20, 1246, 'BB', 'Barbados'),
                    (21, 375, 'BY', 'Bielorrusia'),
                    (22, 32, 'BE', 'Bélgica'),
                    (23, 501, 'BZ', 'Belice'),
                    (24, 229, 'BJ', 'Benin'),
                    (25, 1441, 'BM', 'islas Bermudas'),
                    (26, 975, 'BT', 'Bután'),
                    (27, 591, 'BO', 'Bolivia'),
                    (28, 599, 'BQ', 'Bonaire, Sint Eustatius y Saba'),
                    (29, 387, 'BA', 'Bosnia y Herzegovina'),
                    (30, 267, 'BW', 'Botswana'),
                    (31, 55, 'BV', 'Isla Bouvet'),
                    (32, 55, 'BR', 'Brasil'),
                    (33, 246, 'IO', 'Territorio Británico del Océano Índico'),
                    (34, 673, 'BN', 'Brunei Darussalam'),
                    (35, 359, 'BG', 'Bulgaria'),
                    (36, 226, 'BF', 'Burkina Faso'),
                    (37, 257, 'BI', 'Burundi'),
                    (38, 855, 'KH', 'Camboya'),
                    (39, 237, 'CM', 'Camerún'),
                    (40, 1, 'CA', 'Canadá'),
                    (41, 238, 'CV', 'Cabo Verde'),
                    (42, 1345, 'KY', 'Islas Caimán'),
                    (43, 236, 'CF', 'República Centroafricana'),
                    (44, 235, 'TD', 'Chad'),
                    (45, 56, 'CL', 'Chile'),
                    (46, 86, 'CN', 'porcelana'),
                    (47, 61, 'CX', 'Isla de Navidad'),
                    (48, 672, 'CC', 'Islas Cocos (Keeling)'),
                    (49, 57, 'CO', 'Colombia'),
                    (50, 269, 'KM', 'Comoras'),
                    (51, 242, 'CG', 'Congo'),
                    (52, 242, 'CD', 'Congo, República Democrática del Congo'),
                    (53, 682, 'CK', 'Islas Cook'),
                    (54, 506, 'CR', 'Costa Rica'),
                    (55, 225, 'CI', 'Costa de Marfil'),
                    (56, 385, 'HR', 'Croacia'),
                    (57, 53, 'CU', 'Cuba'),
                    (58, 599, 'CW', 'Curazao'),
                    (59, 357, 'CY', 'Chipre'),
                    (60, 420, 'CZ', 'Republica checa'),
                    (61, 45, 'DK', 'Dinamarca'),
                    (62, 253, 'DJ', 'Djibouti'),
                    (63, 1767, 'DM', 'Dominica'),
                    (64, 1809, 'DO', 'República Dominicana'),
                    (65, 593, 'EC', 'Ecuador'),
                    (66, 20, 'EG', 'Egipto'),
                    (67, 503, 'SV', 'El Salvador'),
                    (68, 240, 'GQ', 'Guinea Ecuatorial'),
                    (69, 291, 'ER', 'Eritrea'),
                    (70, 372, 'EE', 'Estonia'),
                    (71, 251, 'ET', 'Etiopía'),
                    (72, 500, 'FK', 'Islas Falkland (Malvinas)'),
                    (73, 298, 'FO', 'Islas Faroe'),
                    (74, 679, 'FJ', 'Fiyi'),
                    (75, 358, 'FI', 'Finlandia'),
                    (76, 33, 'FR', 'Francia'),
                    (77, 594, 'GF', 'Guayana Francesa'),
                    (78, 689, 'PF', 'Polinesia francés'),
                    (79, 262, 'TF', 'Territorios Franceses del Sur'),
                    (80, 241, 'GA', 'Gabón'),
                    (81, 220, 'GM', 'Gambia'),
                    (82, 995, 'GE', 'Georgia'),
                    (83, 49, 'DE', 'Alemania'),
                    (84, 233, 'GH', 'Ghana'),
                    (85, 350, 'GI', 'Gibraltar'),
                    (86, 30, 'GR', 'Grecia'),
                    (87, 299, 'GL', 'Groenlandia'),
                    (88, 1473, 'GD', 'Granada'),
                    (89, 590, 'GP', 'Guadalupe'),
                    (90, 1671, 'GU', 'Guam'),
                    (91, 502, 'GT', 'Guatemala'),
                    (92, 44, 'GG', 'Guernsey'),
                    (93, 224, 'GN', 'Guinea'),
                    (94, 245, 'GW', 'Guinea-Bissau'),
                    (95, 592, 'GY', 'Guayana'),
                    (96, 509, 'HT', 'Haití'),
                    (97, 0, 'HM', 'Islas Heard y McDonald'),
                    (98, 39, 'VA', 'Santa Sede (Estado de la Ciudad del Vaticano)'),
                    (99, 504, 'HN', 'Honduras'),
                    (100, 852, 'HK', 'Hong Kong'),
                    (101, 36, 'HU', 'Hungría'),
                    (102, 354, 'IS', 'Islandia'),
                    (103, 91, 'IN', 'India'),
                    (104, 62, 'ID', 'Indonesia'),
                    (105, 98, 'IR', 'Irán (República Islámica de'),
                    (106, 964, 'IQ', 'Irak'),
                    (107, 353, 'IE', 'Irlanda'),
                    (108, 44, 'IM', 'Isla del hombre'),
                    (109, 972, 'IL', 'Israel'),
                    (110, 39, 'IT', 'Italia'),
                    (111, 1876, 'JM', 'Jamaica'),
                    (112, 81, 'JP', 'Japón'),
                    (113, 44, 'JE', 'Jersey'),
                    (114, 962, 'JO', 'Jordán'),
                    (115, 7, 'KZ', 'Kazajstán'),
                    (116, 254, 'KE', 'Kenia'),
                    (117, 686, 'KI', 'Kiribati'),
                    (118, 850, 'KP', 'República de Corea, Popular Democrática de'),
                    (119, 82, 'KR', 'Corea, república de'),
                    (120, 381, 'XK', 'Kosovo'),
                    (121, 965, 'KW', 'Kuwait'),
                    (122, 996, 'KG', 'Kirguistán'),
                    (123, 856, 'LA', 'República Democrática Popular Lao'),
                    (124, 371, 'LV', 'Letonia'),
                    (125, 961, 'LB', 'Líbano'),
                    (126, 266, 'LS', 'Lesoto'),
                    (127, 231, 'LR', 'Liberia'),
                    (128, 218, 'LY', 'Jamahiriya Arabe Libia'),
                    (129, 423, 'LI', 'Liechtenstein'),
                    (130, 370, 'LT', 'Lituania'),
                    (131, 352, 'LU', 'Luxemburgo'),
                    (132, 853, 'MO', 'Macao'),
                    (133, 389, 'MK', 'Macedonia, la ex República Yugoslava de'),
                    (134, 261, 'MG', 'Madagascar'),
                    (135, 265, 'MW', 'Malawi'),
                    (136, 60, 'MY', 'Malasia'),
                    (137, 960, 'MV', 'Maldivas'),
                    (138, 223, 'ML', 'Mali'),
                    (139, 356, 'MT', 'Malta'),
                    (140, 692, 'MH', 'Islas Marshall'),
                    (141, 596, 'MQ', 'Martinica'),
                    (142, 222, 'MR', 'Mauritania'),
                    (143, 230, 'MU', 'Mauricio'),
                    (144, 269, 'YT', 'Mayotte'),
                    (145, 52, 'MX', 'México'),
                    (146, 691, 'FM', 'Micronesia, Estados Federados de'),
                    (147, 373, 'MD', 'Moldavia, República de'),
                    (148, 377, 'MC', 'Mónaco'),
                    (149, 976, 'MN', 'Mongolia'),
                    (150, 382, 'ME', 'Montenegro'),
                    (151, 1664, 'MS', 'Montserrat'),
                    (152, 212, 'MA', 'Marruecos'),
                    (153, 258, 'MZ', 'Mozambique'),
                    (154, 95, 'MM', 'Myanmar'),
                    (155, 264, 'NA', 'Namibia'),
                    (156, 674, 'NR', 'Nauru'),
                    (157, 977, 'NP', 'Nepal'),
                    (158, 31, 'NL', 'Países Bajos'),
                    (159, 599, 'AN', 'Antillas Holandesas'),
                    (160, 687, 'NC', 'Nueva Caledonia'),
                    (161, 64, 'NZ', 'Nueva Zelanda'),
                    (162, 505, 'NI', 'Nicaragua'),
                    (163, 227, 'NE', 'Níger'),
                    (164, 234, 'NG', 'Nigeria'),
                    (165, 683, 'NU', 'Niue'),
                    (166, 672, 'NF', 'Isla Norfolk'),
                    (167, 1670, 'MP', 'Islas Marianas del Norte'),
                    (168, 47, 'NO', 'Noruega'),
                    (169, 968, 'OM', 'Omán'),
                    (170, 92, 'PK', 'Pakistán'),
                    (171, 680, 'PW', 'Palau'),
                    (172, 970, 'PS', 'Territorio Palestino, Ocupado'),
                    (173, 507, 'PA', 'Panamá'),
                    (174, 675, 'PG', 'Papúa Nueva Guinea'),
                    (175, 595, 'PY', 'Paraguay'),
                    (176, 51, 'PE', 'Perú'),
                    (177, 63, 'PH', 'Filipinas'),
                    (178, 64, 'PN', 'Pitcairn'),
                    (179, 48, 'PL', 'Polonia'),
                    (180, 351, 'PT', 'Portugal'),
                    (181, 1787, 'PR', 'Puerto Rico'),
                    (182, 974, 'QA', 'Katar'),
                    (183, 262, 'RE', 'Reunión'),
                    (184, 40, 'RO', 'Rumania'),
                    (185, 70, 'RU', 'Federación Rusa'),
                    (186, 250, 'RW', 'Ruanda'),
                    (187, 590, 'BL', 'San Bartolomé'),
                    (188, 290, 'SH', 'Santa elena'),
                    (189, 1869, 'KN', 'Saint Kitts y Nevis'),
                    (190, 1758, 'LC', 'Santa Lucía'),
                    (191, 590, 'MF', 'San Martín'),
                    (192, 508, 'PM', 'San Pedro y Miquelón'),
                    (193, 1784, 'VC', 'San Vicente y las Granadinas'),
                    (194, 684, 'WS', 'Samoa'),
                    (195, 378, 'SM', 'San Marino'),
                    (196, 239, 'ST', 'Santo Tomé y Príncipe'),
                    (197, 966, 'SA', 'Arabia Saudita'),
                    (198, 221, 'SN', 'Senegal'),
                    (199, 381, 'RS', 'Serbia'),
                    (200, 381, 'CS', 'Serbia y Montenegro'),
                    (201, 248, 'SC', 'Seychelles'),
                    (202, 232, 'SL', 'Sierra Leona'),
                    (203, 65, 'SG', 'Singapur'),
                    (204, 1, 'SX', 'San Martín'),
                    (205, 421, 'SK', 'Eslovaquia'),
                    (206, 386, 'SI', 'Eslovenia'),
                    (207, 677, 'SB', 'Islas Salomón'),
                    (208, 252, 'SO', 'Somalia'),
                    (209, 27, 'ZA', 'Sudáfrica'),
                    (210, 500, 'GS', 'Georgia del sur y las islas Sandwich del sur'),
                    (211, 211, 'SS', 'Sudán del Sur'),
                    (212, 34, 'ES', 'España'),
                    (213, 94, 'LK', 'Sri Lanka'),
                    (214, 249, 'SD', 'Sudán'),
                    (215, 597, 'SR', 'Surinam'),
                    (216, 47, 'SJ', 'Svalbard y Jan Mayen'),
                    (217, 268, 'SZ', 'Swazilandia'),
                    (218, 46, 'SE', 'Suecia'),
                    (219, 41, 'CH', 'Suiza'),
                    (220, 963, 'SY', 'República Árabe Siria'),
                    (221, 886, 'TW', 'Taiwan, provincia de China'),
                    (222, 992, 'TJ', 'Tayikistán'),
                    (223, 255, 'TZ', 'Tanzania, República Unida de'),
                    (224, 66, 'TH', 'Tailandia'),
                    (225, 670, 'TL', 'Timor-Leste'),
                    (226, 228, 'TG', 'Para llevar'),
                    (227, 690, 'TK', 'Tokelau'),
                    (228, 676, 'TO', 'Tonga'),
                    (229, 1868, 'TT', 'Trinidad y Tobago'),
                    (230, 216, 'TN', 'Túnez'),
                    (231, 90, 'TR', 'pavo'),
                    (232, 7370, 'TM', 'Turkmenistán'),
                    (233, 1649, 'TC', 'Islas Turcas y Caicos'),
                    (234, 688, 'TV', 'Tuvalu'),
                    (235, 256, 'UG', 'Uganda'),
                    (236, 380, 'UA', 'Ucrania'),
                    (237, 971, 'AE', 'Emiratos Árabes Unidos'),
                    (238, 44, 'GB', 'Reino Unido'),
                    (239, 1, 'US', 'Estados Unidos'),
                    (240, 1, 'UM', 'Islas menores alejadas de los Estados Unidos'),
                    (241, 598, 'UY', 'Uruguay'),
                    (242, 998, 'UZ', 'Uzbekistan'),
                    (243, 678, 'VU', 'Vanuatu'),
                    (244, 58, 'VE', 'Venezuela'),
                    (245, 84, 'VN', 'Vietnam'),
                    (246, 1284, 'VG', 'Islas Vírgenes Británicas'),
                    (247, 1340, 'VI', 'Islas Vírgenes, EE. UU.'),
                    (248, 681, 'WF', 'Wallis y Futuna'),
                    (249, 212, 'EH', 'Sahara Occidental'),
                    (250, 967, 'YE', 'Yemen'),
                    (251, 260, 'ZM', 'Zambia'),
                    (252, 263, 'ZW', 'Zimbabue')";

        DB::select(DB::raw($sql));
    }
}
